server {
    server_name cnc.kavalan.net;

    location / {
        proxy_pass http://127.0.0.1:8091;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300s;
        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        client_max_body_size 10m;
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/cnc.kavalan.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cnc.kavalan.net/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    if ($host = cnc.kavalan.net) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    server_name cnc.kavalan.net;
    return 404;
}
